In [38]:
from population30_40 import cleaned_pop_2030_2040

from population20_29 import cleaned_pop_2020_2029

import pandas as pd

In [43]:
clean_pop_10_19 = pd.read_csv('pop_2010_2019_cleanfile.csv')
clean_pop_10_19

       LocID             Location  Year   AgeGrp      Male    Female
0          4          Afghanistan  2010      0-4  2715.070  2600.535
1          8              Albania  2010      0-4    92.622    81.239
2         12              Algeria  2010      0-4  1966.415  1885.869
3         24               Angola  2010      0-4  2233.041  2239.035
4         28  Antigua and Barbuda  2010      0-4     3.543     3.436
...      ...                  ...   ...      ...       ...       ...
41786    430              Liberia  2019  100-104     0.000     0.000
41787    882                Samoa  2019  100-104     0.000     0.000
41788    768                 Togo  2019  100-104     0.000     0.000
41789    776                Tonga  2019  100-104     0.000     0.000
41790    548              Vanuatu  2019  100-104     0.000     0.000

[41791 rows x 6 columns]

In [44]:

clean_pop_20_29 = cleaned_pop_2020_2029()
clean_pop_20_29

<class 'pandas.DataFrame'>
Index: 41790 entries, 0 to 41794
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LocID     41790 non-null  int64
 1   Location  41790 non-null  str
 2   Year      41790 non-null  int64
 3   AgeGrp    41790 non-null  str
 4   Male      41790 non-null  float64
 5   Female    41790 non-null  float64
dtypes: float64(2), int64(2), str(2)
memory usage: 2.2 MB

       LocID             Location  Year   AgeGrp      Male    Female
0          4          Afghanistan  2020      0-4  2907.406  2765.103
1          8              Albania  2020      0-4    86.564    79.714
2         12              Algeria  2020      0-4  2574.062  2467.456
3         24               Angola  2020      0-4  2923.514  2871.490
4         28  Antigua and Barbuda  2020      0-4     3.730     3.625
...      ...                  ...   ...      ...       ...       ...
41790    430              Liberia  2029  100-104     0.001     0.001
41791    516              Namibia  2029  100-104     0.001     0.003
41792    686              Senegal  2029  100-104     0.001     0.011
41793    690           Seychelles  2029  100-104     0.001     0.006
41794    894               Zambia  2029  100-104     0.001     0.007

[41790 rows x 6 columns]

In [45]:
clean_pop_30_40 = cleaned_pop_2030_2040()
print(clean_pop_30_40)

       LocID             Location  Year   AgeGrp      Male    Female
0          4          Afghanistan  2030      0-4  3020.571  2871.955
1          8              Albania  2030      0-4    68.824    63.581
2         12              Algeria  2030      0-4  2116.681  2026.749
3         24               Angola  2030      0-4  3714.206  3649.187
4         28  Antigua and Barbuda  2030      0-4     3.452     3.354
...      ...                  ...   ...      ...       ...       ...
45971    308              Grenada  2040  100-104     0.001     0.004
45972    426              Lesotho  2040  100-104     0.001     0.009
45973    516              Namibia  2040  100-104     0.001     0.003
45974    690           Seychelles  2040  100-104     0.001     0.007
45975    776                Tonga  2040  100-104     0.001     0.000

[45969 rows x 6 columns]

In [47]:
pop = pd.concat([clean_pop_10_19,clean_pop_20_29,clean_pop_30_40])
pop

       LocID             Location  Year   AgeGrp      Male    Female
0          4          Afghanistan  2010      0-4  2715.070  2600.535
1          8              Albania  2010      0-4    92.622    81.239
2         12              Algeria  2010      0-4  1966.415  1885.869
3         24               Angola  2010      0-4  2233.041  2239.035
4         28  Antigua and Barbuda  2010      0-4     3.543     3.436
...      ...                  ...   ...      ...       ...       ...
45971    308              Grenada  2040  100-104     0.001     0.004
45972    426              Lesotho  2040  100-104     0.001     0.009
45973    516              Namibia  2040  100-104     0.001     0.003
45974    690           Seychelles  2040  100-104     0.001     0.007
45975    776                Tonga  2040  100-104     0.001     0.000

[129550 rows x 6 columns]

In [48]:
pop.describe()

               LocID           Year           Male         Female
count  129550.000000  129550.000000  129550.000000  129550.000000
mean      443.716025    2024.999884     974.498083     959.435828
std       275.310006       8.944369    4434.012159    4139.350891
min         4.000000    2010.000000       0.000000       0.000000
25%       218.000000    2017.000000      10.312250      12.427000
50%       428.000000    2025.000000     107.638500     116.277000
75%       662.000000    2033.000000     508.154000     523.246250
max      1835.000000    2040.000000   67528.067000   62954.207000

In [49]:
## unpivote male and female column

pop.melt(id_vars=['LocID','Location','Year','AgeGrp'],
         value_vars=['Male','Female'],
         var_name='Gender',
         value_name='population')

        LocID             Location  Year   AgeGrp  Gender  population
0           4          Afghanistan  2010      0-4    Male    2715.070
1           8              Albania  2010      0-4    Male      92.622
2          12              Algeria  2010      0-4    Male    1966.415
3          24               Angola  2010      0-4    Male    2233.041
4          28  Antigua and Barbuda  2010      0-4    Male       3.543
...       ...                  ...   ...      ...     ...         ...
259095    308              Grenada  2040  100-104  Female       0.004
259096    426              Lesotho  2040  100-104  Female       0.009
259097    516              Namibia  2040  100-104  Female       0.003
259098    690           Seychelles  2040  100-104  Female       0.007
259099    776                Tonga  2040  100-104  Female       0.000

[259100 rows x 6 columns]

In [ ]:
# Reshape pop so Male/Female columns become rows
# pop_melted = pop.melt(
#     id_vars=[col for col in pop.columns if col not in ['Male', 'Female']],
#     value_vars=['Male', 'Female'],
#     var_name='Gender',
#     value_name='Population'
# )
# pop_melted.head()