# Load all population Data

In [61]:
import pandas as pd

pop_2010_2019_df = pd.read_csv('population-2010-2019.csv',skiprows=1,header = 1,index_col=0)

pop_2010_2019_df

,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
LocID,,,,,,,,
4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
...,...,...,...,...,...,...,...,...
430,Liberia,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
882,Samoa,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
768,Togo,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
776,Tonga,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
548,Vanuatu,2019.0,100+,100.0,-1.0,0.000,0.000,0.000

# Find data details

## 1. Essential Properties (Attributes)
  Properties tell you something about the data without changing it. You don't use parentheses () with these.

  | Property | Description | SQL/Power BI Equivalent |
| :--- | :--- | :--- |
| **`.shape`** | Returns a tuple (rows, columns). | Table Row/Col count |
| **`.columns`** | Returns the list of column names. | Header Row |
| **`.index`** | Returns the row labels (usually 0, 1, 2...). | Primary Key/Index |
| **`.dtypes`** | Shows the data type of each column. | Schema / Data Category |
| **`.size`** | Total number of elements (rows × columns). | Total Cell Count |
| **`.values`** | Converts the data into a NumPy array. | Raw Data Array |

In [62]:
pop_2010_2019_df.shape

(41795, 8)

In [63]:
pop_2010_2019_df.columns

Index(['Location', 'Time', 'AgeGrp', 'AgeGrpStart', 'AgeGrpSpan', 'PopMale',
       'PopFemale', 'PopTotal'],
      dtype='str')

In [64]:
pop_2010_2019_df.index

Index([  4,   8,  12,  24,  28,  32,  51, 533,  36,  40,
       ...
       226, 266, 270, 624, 414, 430, 882, 768, 776, 548],
      dtype='int64', name='LocID', length=41795)

In [65]:
pop_2010_2019_df.dtypes

Location           str
Time           float64
AgeGrp             str
AgeGrpStart    float64
AgeGrpSpan     float64
PopMale        float64
PopFemale      float64
PopTotal       float64
dtype: object

In [66]:
pop_2010_2019_df.size

334360

In [67]:
pop_2010_2019_df.values

array([['Afghanistan', 2010.0, '0-4', ..., 2715.07, 2600.535, 5315.605],
       ['Albania', 2010.0, '0-4', ..., 92.622, 81.239, 173.861],
       ['Algeria', 2010.0, '0-4', ..., 1966.415, 1885.869, 3852.284],
       ...,
       ['Togo', 2019.0, '100+', ..., 0.0, 0.0, 0.0],
       ['Tonga', 2019.0, '100+', ..., 0.0, 0.0, 0.0],
       ['Vanuatu', 2019.0, '100+', ..., 0.0, 0.0, 0.0]],
      shape=(41795, 8), dtype=object)

## 2. Essential Methods
Methods perform an action or calculation on the data. These always use parentheses ().

**A. Data Exploration**
* **.head(n) / .tail(n):** View the first or last (n) rows.
* **.info():** A "health check" for your data. Shows non-null counts and memory usage.
* **.describe():** Generates summary statistics (mean, std, min, max, quartiles).

-Power BI Equivalent: Column Statistics in Power Query.

In [68]:
pop_2010_2019_df.head(10)

,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
LocID,,,,,,,,
4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
32,Argentina,2010.0,0-4,0.0,5.0,1836.187,1769.816,3606.003
51,Armenia,2010.0,0-4,0.0,5.0,107.368,93.715,201.083
533,Aruba,2010.0,0-4,0.0,5.0,3.402,3.257,6.659
36,Australia,2010.0,0-4,0.0,5.0,750.450,711.435,1461.885
40,Austria,2010.0,0-4,0.0,5.0,200.530,190.404,390.934

In [69]:
pop_2010_2019_df.tail(10)

,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
LocID,,,,,,,,
226,Equatorial Guinea,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
266,Gabon,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
270,Gambia,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
624,Guinea-Bissau,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
414,Kuwait,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
430,Liberia,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
882,Samoa,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
768,Togo,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
776,Tonga,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
548,Vanuatu,2019.0,100+,100.0,-1.0,0.0,0.0,0.0

In [70]:
pop_2010_2019_df.info()

<class 'pandas.DataFrame'>
Index: 41795 entries, 4 to 548
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     41795 non-null  str
 1   Time         41791 non-null  float64
 2   AgeGrp       41791 non-null  str
 3   AgeGrpStart  41791 non-null  float64
 4   AgeGrpSpan   41791 non-null  float64
 5   PopMale      41791 non-null  float64
 6   PopFemale    41791 non-null  float64
 7   PopTotal     41791 non-null  float64
dtypes: float64(6), str(2)
memory usage: 2.9 MB

In [71]:
pop_2010_2019_df.describe()

,Time,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
count,41791.000000,41791.000000,41791.000000,41791.000000,41791.000000,41791.000000
mean,2014.499892,49.998804,4.714293,878.579738,863.585655,1742.165369
std,2.872366,30.277491,1.277754,4280.236638,3978.122164,8255.389397
min,2010.000000,0.000000,-1.000000,0.000000,0.000000,0.000000
25%,2012.000000,25.000000,5.000000,8.154500,10.138500,18.930500
50%,2014.000000,50.000000,5.000000,87.610000,99.380000,190.152000
75%,2017.000000,75.000000,5.000000,415.091000,434.783500,852.304500
max,2019.000000,100.000000,5.000000,67528.067000,62954.207000,130144.737000

**B. Data Selection & Filtering**
* **.loc[]:** Access rows and columns by label (e.g., df.loc[0, 'Name']). --- only works on index col..far left col

* **.iloc[]:** Access rows and columns by integer position (e.g., df.iloc[0, 1]).

* **.drop():** Removes specified rows or columns.

In [72]:
pop_2010_2019_df.loc[226]

,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
LocID,,,,,,,,
226,Equatorial Guinea,2010.0,0-4,0.0,5.0,75.527,73.608,149.135
226,Equatorial Guinea,2010.0,05. Sep,5.0,5.0,60.073,58.571,118.644
226,Equatorial Guinea,2010.0,Okt 14,10.0,5.0,48.377,47.167,95.544
226,Equatorial Guinea,2010.0,15-19,15.0,5.0,41.640,38.928,80.568
226,Equatorial Guinea,2010.0,20-24,20.0,5.0,52.981,40.023,93.004
...,...,...,...,...,...,...,...,...
226,Equatorial Guinea,2015.0,100+,100.0,-1.0,0.000,0.000,0.000
226,Equatorial Guinea,2016.0,100+,100.0,-1.0,0.000,0.000,0.000
226,Equatorial Guinea,2017.0,100+,100.0,-1.0,0.000,0.000,0.000
226,Equatorial Guinea,2018.0,100+,100.0,-1.0,0.000,0.000,0.000
226,Equatorial Guinea,2019.0,100+,100.0,-1.0,0.000,0.000,0.000

In [73]:
print(pop_2010_2019_df.iloc[1])
print("=="*12)
print(pop_2010_2019_df.iloc[0])

Location       Albania
Time            2010.0
AgeGrp             0-4
AgeGrpStart        0.0
AgeGrpSpan         5.0
PopMale         92.622
PopFemale       81.239
PopTotal       173.861
Name: 8, dtype: object
========================
Location       Afghanistan
Time                2010.0
AgeGrp                 0-4
AgeGrpStart            0.0
AgeGrpSpan             5.0
PopMale            2715.07
PopFemale         2600.535
PopTotal          5315.605
Name: 4, dtype: object

**C. Data Cleaning**
* **.isnull() / .notnull():** Returns a boolean mask for missing values.

* **.fillna(value):** Replaces NaN values with a specific value.

--SQL Equivalent: COALESCE(column, value).

* **.dropna():** Deletes rows/columns containing missing values.

* **.rename():** Changes column or index names.

In [74]:
pop_2010_2019_df.isnull()

,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
LocID,,,,,,,,
4,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
430,False,False,False,False,False,False,False,False
882,False,False,False,False,False,False,False,False
768,False,False,False,False,False,False,False,False
776,False,False,False,False,False,False,False,False
548,False,False,False,False,False,False,False,False

In [75]:
pop_2010_2019_df.isnull().any()

Location       False
Time            True
AgeGrp          True
AgeGrpStart     True
AgeGrpSpan      True
PopMale         True
PopFemale       True
PopTotal        True
dtype: bool

In [76]:
pop_2010_2019_df.isnull().any(axis=1)

LocID
4      False
8      False
12     False
24     False
28     False
       ...
430    False
882    False
768    False
776    False
548    False
Length: 41795, dtype: bool

## Clean1

In [77]:
pop_2010_2019_df[pop_2010_2019_df.isnull().any(axis = 1)]  ## how to keep this in mind

,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
LocID,,,,,,,,
111,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
pop_2010_2019_df.dropna(inplace=True) ## inplace makes method to work in place

In [79]:
pop_2010_2019_df[pop_2010_2019_df.isnull().any(axis = 1)]  ## This tells us nulls are removed

Empty DataFrame
Columns: [Location, Time, AgeGrp, AgeGrpStart, AgeGrpSpan, PopMale, PopFemale, PopTotal]
Index: []

In [80]:
pop_2010_2019_df.head(10)

,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
LocID,,,,,,,,
4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
32,Argentina,2010.0,0-4,0.0,5.0,1836.187,1769.816,3606.003
51,Armenia,2010.0,0-4,0.0,5.0,107.368,93.715,201.083
533,Aruba,2010.0,0-4,0.0,5.0,3.402,3.257,6.659
36,Australia,2010.0,0-4,0.0,5.0,750.450,711.435,1461.885
40,Austria,2010.0,0-4,0.0,5.0,200.530,190.404,390.934

In [89]:
pop_2010_2019_df.rename(columns={'Time':'Year','PopMale':'Male','PopFemale':'Female'},inplace=True)
pop_2010_2019_df

,Location,Year,AgeGrp,AgeGrpStart,AgeGrpSpan,Male,Female,PopTotal
LocID,,,,,,,,
4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
...,...,...,...,...,...,...,...,...
430,Liberia,2019.0,100-104,100.0,-1.0,0.000,0.000,0.000
882,Samoa,2019.0,100-104,100.0,-1.0,0.000,0.000,0.000
768,Togo,2019.0,100-104,100.0,-1.0,0.000,0.000,0.000
776,Tonga,2019.0,100-104,100.0,-1.0,0.000,0.000,0.000
548,Vanuatu,2019.0,100-104,100.0,-1.0,0.000,0.000,0.000

In [81]:
pop_2010_2019_df['AgeGrp'].unique()

<StringArray>
[      '0-4',   '05. Sep',    'Okt 14',     '15-19',     '20-24',     '25-29',
     '30-34',     '35-39',     '40-44',     '45-49',     '50-54',     '55-59',
     '60-64',     '65-69',     '70-74',     '75-79',     '80-84',     '85-89',
     '90-94', '905. Sep9',      '100+']
Length: 21, dtype: str

In [84]:
pop_2010_2019_df.replace({'AgeGrp':{'05. Sep':'5-10','Okt 14':'11-14','905. Sep9':'95-99','100+':'100-104'}},inplace=True)
pop_2010_2019_df.head()

,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
LocID,,,,,,,,
4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979

In [85]:
pop_2010_2019_df['AgeGrp'].unique()

<StringArray>
[    '0-4',    '5-10',   '11-14',   '15-19',   '20-24',   '25-29',   '30-34',
   '35-39',   '40-44',   '45-49',   '50-54',   '55-59',   '60-64',   '65-69',
   '70-74',   '75-79',   '80-84',   '85-89',   '90-94',   '95-99', '100-104']
Length: 21, dtype: str

**D. Data Transformation**
* **.groupby():** Groups data by a column to perform aggregations.

--SQL Equivalent: GROUP BY.

* **.sort_values():** Sorts the data by one or more columns.

--SQL Equivalent: ORDER BY.

* **.apply():** Applies a function (like a Lambda) to every element in a column.

--Power BI Equivalent: Custom Column using Power Query M.