# Load all population Data

In [37]:
import pandas as pd

pop_2010_2019_df = pd.read_csv('original_data/population-2010-2019.csv',skiprows=1,header = 1)

pop_2010_2019_df

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
0,4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
1,8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
2,12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
3,24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
4,28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
...,...,...,...,...,...,...,...,...,...
41790,430,Liberia,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
41791,882,Samoa,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
41792,768,Togo,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
41793,776,Tonga,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
41794,548,Vanuatu,2019.0,100+,100.0,-1.0,0.000,0.000,0.000

# Find data details

## 1. Essential Properties (Attributes)
  Properties tell you something about the data without changing it. You don't use parentheses () with these.

  | Property | Description | SQL/Power BI Equivalent |
| :--- | :--- | :--- |
| **`.shape`** | Returns a tuple (rows, columns). | Table Row/Col count |
| **`.columns`** | Returns the list of column names. | Header Row |
| **`.index`** | Returns the row labels (usually 0, 1, 2...). | Primary Key/Index |
| **`.dtypes`** | Shows the data type of each column. | Schema / Data Category |
| **`.size`** | Total number of elements (rows × columns). | Total Cell Count |
| **`.values`** | Converts the data into a NumPy array. | Raw Data Array |

In [38]:
pop_2010_2019_df.shape

(41795, 9)

In [39]:
pop_2010_2019_df.columns

Index(['LocID', 'Location', 'Time', 'AgeGrp', 'AgeGrpStart', 'AgeGrpSpan',
       'PopMale', 'PopFemale', 'PopTotal'],
      dtype='str')

In [40]:
pop_2010_2019_df.index

RangeIndex(start=0, stop=41795, step=1)

In [41]:
pop_2010_2019_df.dtypes

LocID            int64
Location           str
Time           float64
AgeGrp             str
AgeGrpStart    float64
AgeGrpSpan     float64
PopMale        float64
PopFemale      float64
PopTotal       float64
dtype: object

In [42]:
pop_2010_2019_df.size

376155

In [43]:
pop_2010_2019_df.values

array([[4, 'Afghanistan', 2010.0, ..., 2715.07, 2600.535, 5315.605],
       [8, 'Albania', 2010.0, ..., 92.622, 81.239, 173.861],
       [12, 'Algeria', 2010.0, ..., 1966.415, 1885.869, 3852.284],
       ...,
       [768, 'Togo', 2019.0, ..., 0.0, 0.0, 0.0],
       [776, 'Tonga', 2019.0, ..., 0.0, 0.0, 0.0],
       [548, 'Vanuatu', 2019.0, ..., 0.0, 0.0, 0.0]],
      shape=(41795, 9), dtype=object)

## 2. Essential Methods
Methods perform an action or calculation on the data. These always use parentheses ().

**A. Data Exploration**
* **.head(n) / .tail(n):** View the first or last (n) rows.
* **.info():** A "health check" for your data. Shows non-null counts and memory usage.
* **.describe():** Generates summary statistics (mean, std, min, max, quartiles).

-Power BI Equivalent: Column Statistics in Power Query.

In [44]:
pop_2010_2019_df.head(10)

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
0,4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
1,8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
2,12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
3,24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
4,28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
5,32,Argentina,2010.0,0-4,0.0,5.0,1836.187,1769.816,3606.003
6,51,Armenia,2010.0,0-4,0.0,5.0,107.368,93.715,201.083
7,533,Aruba,2010.0,0-4,0.0,5.0,3.402,3.257,6.659
8,36,Australia,2010.0,0-4,0.0,5.0,750.450,711.435,1461.885
9,40,Austria,2010.0,0-4,0.0,5.0,200.530,190.404,390.934

In [45]:
pop_2010_2019_df.tail(10)

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
41785,226,Equatorial Guinea,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41786,266,Gabon,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41787,270,Gambia,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41788,624,Guinea-Bissau,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41789,414,Kuwait,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41790,430,Liberia,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41791,882,Samoa,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41792,768,Togo,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41793,776,Tonga,2019.0,100+,100.0,-1.0,0.0,0.0,0.0
41794,548,Vanuatu,2019.0,100+,100.0,-1.0,0.0,0.0,0.0

In [46]:
pop_2010_2019_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41795 entries, 0 to 41794
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   LocID        41795 non-null  int64
 1   Location     41795 non-null  str
 2   Time         41791 non-null  float64
 3   AgeGrp       41791 non-null  str
 4   AgeGrpStart  41791 non-null  float64
 5   AgeGrpSpan   41791 non-null  float64
 6   PopMale      41791 non-null  float64
 7   PopFemale    41791 non-null  float64
 8   PopTotal     41791 non-null  float64
dtypes: float64(6), int64(1), str(2)
memory usage: 2.9 MB

In [47]:
pop_2010_2019_df.describe()

,LocID,Time,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
count,41795.000000,41791.000000,41791.000000,41791.000000,41791.000000,41791.000000,41791.000000
mean,443.678789,2014.499892,49.998804,4.714293,878.579738,863.585655,1742.165369
std,275.319329,2.872366,30.277491,1.277754,4280.236638,3978.122164,8255.389397
min,4.000000,2010.000000,0.000000,-1.000000,0.000000,0.000000,0.000000
25%,218.000000,2012.000000,25.000000,5.000000,8.154500,10.138500,18.930500
50%,428.000000,2014.000000,50.000000,5.000000,87.610000,99.380000,190.152000
75%,662.000000,2017.000000,75.000000,5.000000,415.091000,434.783500,852.304500
max,1835.000000,2019.000000,100.000000,5.000000,67528.067000,62954.207000,130144.737000

**B. Data Selection & Filtering**
* **.loc[]:** Access rows and columns by label (e.g., df.loc[0, 'Name']). --- only works on index col..far left col

* **.iloc[]:** Access rows and columns by integer position (e.g., df.iloc[0, 1]).

* **.drop():** Removes specified rows or columns.

In [48]:
pop_2010_2019_df.loc[226]

LocID                72
Location       Botswana
Time             2010.0
AgeGrp          05. Sep
AgeGrpStart         5.0
AgeGrpSpan          5.0
PopMale         116.448
PopFemale       114.062
PopTotal         230.51
Name: 226, dtype: object

In [49]:
print(pop_2010_2019_df.iloc[1])
print("=="*12)
print(pop_2010_2019_df.iloc[0])

LocID                8
Location       Albania
Time            2010.0
AgeGrp             0-4
AgeGrpStart        0.0
AgeGrpSpan         5.0
PopMale         92.622
PopFemale       81.239
PopTotal       173.861
Name: 1, dtype: object
========================
LocID                    4
Location       Afghanistan
Time                2010.0
AgeGrp                 0-4
AgeGrpStart            0.0
AgeGrpSpan             5.0
PopMale            2715.07
PopFemale         2600.535
PopTotal          5315.605
Name: 0, dtype: object

**C. Data Cleaning**
* **.isnull() / .notnull():** Returns a boolean mask for missing values.

* **.fillna(value):** Replaces NaN values with a specific value.

--SQL Equivalent: COALESCE(column, value).

* **.dropna():** Deletes rows/columns containing missing values.

* **.rename():** Changes column or index names.

In [50]:
pop_2010_2019_df.isnull()

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
41790,False,False,False,False,False,False,False,False,False
41791,False,False,False,False,False,False,False,False,False
41792,False,False,False,False,False,False,False,False,False
41793,False,False,False,False,False,False,False,False,False
41794,False,False,False,False,False,False,False,False,False

In [51]:
pop_2010_2019_df.isnull().any()

LocID          False
Location       False
Time            True
AgeGrp          True
AgeGrpStart     True
AgeGrpSpan      True
PopMale         True
PopFemale       True
PopTotal        True
dtype: bool

In [52]:
pop_2010_2019_df.isnull().any(axis=1)

0        False
1        False
2        False
3        False
4        False
         ...
41790    False
41791    False
41792    False
41793    False
41794    False
Length: 41795, dtype: bool

## Clean1

In [53]:
pop_2010_2019_df[pop_2010_2019_df.isnull().any(axis = 1)]  ## how to keep this in mind

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
40,111,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,111,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,111,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,111,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
pop_2010_2019_df.dropna(inplace=True) ## inplace makes method to work in place

In [55]:
pop_2010_2019_df[pop_2010_2019_df.isnull().any(axis = 1)]  ## This tells us nulls are removed

Empty DataFrame
Columns: [LocID, Location, Time, AgeGrp, AgeGrpStart, AgeGrpSpan, PopMale, PopFemale, PopTotal]
Index: []

In [56]:
pop_2010_2019_df.head(10)

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
0,4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
1,8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
2,12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
3,24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
4,28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
5,32,Argentina,2010.0,0-4,0.0,5.0,1836.187,1769.816,3606.003
6,51,Armenia,2010.0,0-4,0.0,5.0,107.368,93.715,201.083
7,533,Aruba,2010.0,0-4,0.0,5.0,3.402,3.257,6.659
8,36,Australia,2010.0,0-4,0.0,5.0,750.450,711.435,1461.885
9,40,Austria,2010.0,0-4,0.0,5.0,200.530,190.404,390.934

In [57]:
pop_2010_2019_df.rename(columns={'Time':'Year','PopMale':'Male','PopFemale':'Female'},inplace=True)
pop_2010_2019_df

,LocID,Location,Year,AgeGrp,AgeGrpStart,AgeGrpSpan,Male,Female,PopTotal
0,4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
1,8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
2,12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
3,24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
4,28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
...,...,...,...,...,...,...,...,...,...
41790,430,Liberia,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
41791,882,Samoa,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
41792,768,Togo,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
41793,776,Tonga,2019.0,100+,100.0,-1.0,0.000,0.000,0.000
41794,548,Vanuatu,2019.0,100+,100.0,-1.0,0.000,0.000,0.000

In [58]:
pop_2010_2019_df['AgeGrp'].unique()

<StringArray>
[      '0-4',   '05. Sep',    'Okt 14',     '15-19',     '20-24',     '25-29',
     '30-34',     '35-39',     '40-44',     '45-49',     '50-54',     '55-59',
     '60-64',     '65-69',     '70-74',     '75-79',     '80-84',     '85-89',
     '90-94', '905. Sep9',      '100+']
Length: 21, dtype: str

In [59]:
pop_2010_2019_df.replace({'AgeGrp':{'05. Sep':'5-10','Okt 14':'11-14','905. Sep9':'95-99','100+':'100-104'}},inplace=True)
pop_2010_2019_df.head()

,LocID,Location,Year,AgeGrp,AgeGrpStart,AgeGrpSpan,Male,Female,PopTotal
0,4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
1,8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
2,12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
3,24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
4,28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979

In [60]:
pop_2010_2019_df['AgeGrp'].unique()

<StringArray>
[    '0-4',    '5-10',   '11-14',   '15-19',   '20-24',   '25-29',   '30-34',
   '35-39',   '40-44',   '45-49',   '50-54',   '55-59',   '60-64',   '65-69',
   '70-74',   '75-79',   '80-84',   '85-89',   '90-94',   '95-99', '100-104']
Length: 21, dtype: str

**D. Data Transformation**
* **.groupby():** Groups data by a column to perform aggregations.

--SQL Equivalent: GROUP BY.

* **.sort_values():** Sorts the data by one or more columns.

--SQL Equivalent: ORDER BY.

* **.apply():** Applies a function (like a Lambda) to every element in a column.

--Power BI Equivalent: Custom Column using Power Query M.

In [61]:
pop_2010_2019_df.head(10)

,LocID,Location,Year,AgeGrp,AgeGrpStart,AgeGrpSpan,Male,Female,PopTotal
0,4,Afghanistan,2010.0,0-4,0.0,5.0,2715.070,2600.535,5315.605
1,8,Albania,2010.0,0-4,0.0,5.0,92.622,81.239,173.861
2,12,Algeria,2010.0,0-4,0.0,5.0,1966.415,1885.869,3852.284
3,24,Angola,2010.0,0-4,0.0,5.0,2233.041,2239.035,4472.076
4,28,Antigua and Barbuda,2010.0,0-4,0.0,5.0,3.543,3.436,6.979
5,32,Argentina,2010.0,0-4,0.0,5.0,1836.187,1769.816,3606.003
6,51,Armenia,2010.0,0-4,0.0,5.0,107.368,93.715,201.083
7,533,Aruba,2010.0,0-4,0.0,5.0,3.402,3.257,6.659
8,36,Australia,2010.0,0-4,0.0,5.0,750.450,711.435,1461.885
9,40,Austria,2010.0,0-4,0.0,5.0,200.530,190.404,390.934

In [62]:
pop_2010_2019_df.info()

<class 'pandas.DataFrame'>
Index: 41791 entries, 0 to 41794
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   LocID        41791 non-null  int64
 1   Location     41791 non-null  str
 2   Year         41791 non-null  float64
 3   AgeGrp       41791 non-null  str
 4   AgeGrpStart  41791 non-null  float64
 5   AgeGrpSpan   41791 non-null  float64
 6   Male         41791 non-null  float64
 7   Female       41791 non-null  float64
 8   PopTotal     41791 non-null  float64
dtypes: float64(6), int64(1), str(2)
memory usage: 3.2 MB

In [63]:
##pop_2010_2019_df['Year'] = pd.to_datetime(pop_2010_2019_df['Year'], format='%Y')
#  ---It give 01-01 date to all the rows which is wrong

In [64]:
pop_2010_2019_df['Year'] = pop_2010_2019_df['Year'].astype(int)
pop_2010_2019_df.info()

<class 'pandas.DataFrame'>
Index: 41791 entries, 0 to 41794
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   LocID        41791 non-null  int64
 1   Location     41791 non-null  str
 2   Year         41791 non-null  int64
 3   AgeGrp       41791 non-null  str
 4   AgeGrpStart  41791 non-null  float64
 5   AgeGrpSpan   41791 non-null  float64
 6   Male         41791 non-null  float64
 7   Female       41791 non-null  float64
 8   PopTotal     41791 non-null  float64
dtypes: float64(5), int64(2), str(2)
memory usage: 3.2 MB

In [65]:
pop_2010_2019_df.head(10)

,LocID,Location,Year,AgeGrp,AgeGrpStart,AgeGrpSpan,Male,Female,PopTotal
0,4,Afghanistan,2010,0-4,0.0,5.0,2715.070,2600.535,5315.605
1,8,Albania,2010,0-4,0.0,5.0,92.622,81.239,173.861
2,12,Algeria,2010,0-4,0.0,5.0,1966.415,1885.869,3852.284
3,24,Angola,2010,0-4,0.0,5.0,2233.041,2239.035,4472.076
4,28,Antigua and Barbuda,2010,0-4,0.0,5.0,3.543,3.436,6.979
5,32,Argentina,2010,0-4,0.0,5.0,1836.187,1769.816,3606.003
6,51,Armenia,2010,0-4,0.0,5.0,107.368,93.715,201.083
7,533,Aruba,2010,0-4,0.0,5.0,3.402,3.257,6.659
8,36,Australia,2010,0-4,0.0,5.0,750.450,711.435,1461.885
9,40,Austria,2010,0-4,0.0,5.0,200.530,190.404,390.934

In [66]:
pop_2010_2019_df.drop(columns = ['AgeGrpStart','AgeGrpSpan','PopTotal'],inplace = True)
pop_2010_2019_df.head(5)

   LocID             Location  Year AgeGrp      Male    Female
0      4          Afghanistan  2010    0-4  2715.070  2600.535
1      8              Albania  2010    0-4    92.622    81.239
2     12              Algeria  2010    0-4  1966.415  1885.869
3     24               Angola  2010    0-4  2233.041  2239.035
4     28  Antigua and Barbuda  2010    0-4     3.543     3.436

In [67]:
pop_2010_2019_df.describe()

              LocID          Year          Male        Female
count  41791.000000  41791.000000  41791.000000  41791.000000
mean     443.710631   2014.499892    878.579738    863.585655
std      275.313265      2.872366   4280.236638   3978.122164
min        4.000000   2010.000000      0.000000      0.000000
25%      218.000000   2012.000000      8.154500     10.138500
50%      428.000000   2014.000000     87.610000     99.380000
75%      662.000000   2017.000000    415.091000    434.783500
max     1835.000000   2019.000000  67528.067000  62954.207000

In [ ]:
#pop_2010_2019_df.to_csv('cleaned_data/pop_2010_2019_cleanfile.csv',index=False)